// Authentication & Account Lockout
const AUTH_CONSTANTS = {
  MAX_FAILED_ATTEMPTS: 5,
  LOCK_DURATION_MS: 15 * 60 * 1000,
  OTP_TTL_SECONDS: 2 * 60,
  RESET_PASSWORD_TOKEN_TTL_SECONDS: 10 * 60,
  REFRESH_TOKEN_EXPIRY_DAYS: 7,
  ACCESS_TOKEN_EXPIRY: "15m",
};

// Chat & Presence
const CHAT_CONSTANTS = {
  CHAT_TTL: 24 * 60 * 60,
  CACHE_SIZE: 30,
  PRESENCE_TTL: 24 * 60 * 60,
  ACTIVE_TAB_TTL: 24 * 60 * 60,
};

module.exports = {
  AUTH_CONSTANTS,
  CHAT_CONSTANTS,
};
